// <auto-generated />
namespace TheIronYard.Models.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Deparmentalization : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Deparmentalization));
        
        string IMigrationMetadata.Id
        {
            get { return "201702011550064_Deparmentalization"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
